apps/routes/ticket.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    current_app,
    request
)

from flask_login import current_user, login_required

from apps.models import Ticket, Roles, Group
from apps.forms import UpdateTicket, CreateTicket
from apps.utils import role_required, user_in_ticket_group
from apps import db


ticket_bl = Blueprint("ticket", __name__)


@ticket_bl.get("/tickets/")
@login_required
@role_required([Roles.admin, Roles.manager, Roles.analyst])
def list_ticket():
    """
    Get tickets from current user assigned groups
    or if you admin see all
    """
    page = request.args.get("page", 1, type=int)

    tickets = Ticket.query

    if current_user.role != Roles.admin:
        # admin can view everything
        # Get all groups the current user is assigned to
        user_groups = current_user.groups

        # Collect all tickets associated with these groups
        tickets = Ticket.query.join(Ticket.assigned_groups).filter(
            Group.id.in_([group.id for group in user_groups])
        )

    # paginate
    tickets = tickets.paginate(
        page=page,
        max_per_page=current_app.config.get("PAGINATION_MAX_PER_PAGE"),
        error_out=False,
    )
    return render_template(
        "tickets/ticket_list.html",
        tickets=tickets,
        pagination=tickets,
    )


@ticket_bl.get("/tickets/<int:ticket_id>")
@login_required
@role_required([Roles.admin, Roles.analyst, Roles.manager])
@user_in_ticket_group
def detail_ticket(ticket_id: int):
    ticket = Ticket.query.get_or_404(ticket_id)
    return render_template("tickets/ticket_detail.html", ticket=ticket)


@ticket_bl.route("/tickets/create", methods=["GET", "POST"])
@login_required
@role_required([Roles.admin])
def create_ticket():
    form = CreateTicket()

    if form.validate_on_submit():
        status = form.status.data
        note = form.note.data
        assigned_groups = form.assigned_groups.data
        assigned_user = form.assigned_user.data

        ticket = Ticket(status=status, note=note, assigned_user=assigned_user)
        ticket.assigned_groups.extend(assigned_groups)

        db.session.add(ticket)
        db.session.commit()

        return redirect(url_for("ticket.list_ticket"))

    return render_template("tickets/ticket_form.html", form=form)


@ticket_bl.route("/tickets/<int:ticket_id>/update", methods=["GET", "POST"])
@login_required
@role_required([Roles.admin, Roles.analyst, Roles.manager])
@user_in_ticket_group
def update_ticket(ticket_id: int):
    ticket = Ticket.query.get_or_404(ticket_id)
    form = UpdateTicket(obj=ticket)

    if form.validate_on_submit():
        ticket.status = form.status.data
        ticket.assigned_groups = form.assigned_groups.data
        ticket.assigned_user = form.assigned_user.data

        db.session.add(ticket)
        db.session.commit()

        return redirect(url_for("ticket.detail_ticket", ticket_id=ticket_id))

    return render_template(
        "tickets/ticket_form.html",
        ticket=ticket,
        form=form
    )


@ticket_bl.delete("/tickets/<int:ticket_id>")
@login_required
@role_required([Roles.admin, Roles.analyst, Roles.manager])
@user_in_ticket_group
def delete_ticket(ticket_id: int):
    ticket = Ticket.query.get_or_404(ticket_id)
    db.session.delete(ticket)
    db.session.commit()

    return redirect(url_for("ticket.list_ticket"))

apps/templates/tickets/ticket_detail.html
{% extends "layouts/base.html" %}

{% block title %}
  Ticket
{% endblock %}

{% block content %}
  <div class="container mt-8">
    <h1>
      Ticket
      <a href="{{ url_for('ticket.update_ticket', ticket_id=ticket.id) }}" class="btn btn-primary"> Update</a>
      <a href="{{ url_for('ticket.delete_ticket', ticket_id=ticket.id) }}" class="btn btn-danger"> Delete</a>
    </h1>

    <p><strong>Status: </strong>{{ ticket.status.value }}</p>
    <p><strong>Note: </strong>{{ ticket.note }}</p>
    <hr>
    <p><strong>Groups: </strong></p>
    {% for group in ticket.assigned_groups %}
      <p><a href="{{ url_for('group.list_group', ticket_id=ticket.id) }}"> {{ group.name }}</a></p>
    {% endfor %}
  </div>
{% endblock %}

apps/templates/tickets/ticket_form.html
{% extends "layouts/base.html" %}

{% block title %}
    {% if ticket %}Update{% else %}Create{% endif %} Ticket
{% endblock %}

{% block content %}
<div class="container  mt-8">
    <h1>{% if ticket %}Update{% else %}Create{% endif %} Ticket</h1>

    <div class="card-body">

        <form role="form" method="post" action="">
            {{ form.csrf_token }}
            {{ form.hidden_tag() }}

            <div class="form-group">
                <label class="small mb-1" for="status">Status</label>
                {{ form.status(class="form-select") }}
            </div>
            <div class="form-group">
                <label class="small mb-1" for="note">Note</label>
                {{ form.note(placeholder="Ticket note", class="form-control") }}
            </div>
            <div class="form-group">
                <label class="small mb-1" for="assigned_groups">Assigned to Groups</label>
                {{ form.assigned_groups(class="form-select", multiple="multiple") }}
            </div>
            <div class="form-group">
                <label class="small mb-1" for="assigned_user">Assigned to User</label>
                {{ form.assigned_user(class="form-select") }}
            </div>
            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                {{ form.submit(class_='btn btn-primary') }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

apps/templates/tickets/ticket_list.html
{% extends "layouts/base.html" %}

{% block title %} Tickets {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Tickets</h1>

        <div class="card mb-4">
            <div class="card-header">
              <i class="fas fa-table me-1"></i>
              Ticket table
              {% if current_user.role.value == 'Admin' %}
                <span><a href="{{ url_for('ticket.create_ticket') }}">Create</a></span>
              {% endif %}
            </div>
            <div class="card-body">
                <table id="datatablesSimple">
                  <thead>
                      <tr>
                          <th>ID</th>
                          <th>Status</th>
                      </tr>
                  </thead>
                  <tfoot>
                      <tr>
                          <th>ID</th>
                          <th>Status</th>
                      </tr>
                  </tfoot>
                  <tbody>
                    {% for ticket in tickets %}
                      <tr>
                        <td>
                          <a
                            href="{{ url_for('ticket.detail_ticket', ticket_id=ticket.id) }}">{{ ticket.id }}
                          </a>
                        </td>
                        <td>{{ ticket.status }}</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
      {% include 'includes/pagination.html' %}
    </div>
  </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script>
        window.addEventListener('DOMContentLoaded', event => {
            const datatablesSimple = document.getElementById('datatablesSimple');
            if (datatablesSimple) {
                new simpleDatatables.DataTable(datatablesSimple, {
                    paging: false, // Disable pagination
                    searchable: false, // Disable search
                });
            }
        });
    </script>

{% endblock javascripts %}