apps/routes/user.py
from flask import (
    Blueprint,
    render_template,
    flash,
    redirect,
    url_for,
    current_app,
    request,
)

from flask_login import current_user, login_required

from apps.models import User, Group, Roles
from apps.forms import UpdateUser, AdminUpdateUser
from apps import db
from apps.utils import role_required


user_bl = Blueprint("user", __name__)

# Endpoints for User model


@user_bl.get("/")
def index():
    return "Hello"


@user_bl.get("/users/me")
@login_required
def view_me():
    return render_template("users/user_detail.html", user=current_user)


@user_bl.route("/users/me/edit", methods=["GET", "PATCH"])
@login_required
def update_me():
    form = UpdateUser(obj=current_user)
    if form.validate_on_submit():
        current_user.username = form.username.data
        db.session.add(current_user)
        db.session.commit()

        flash("Your changes have been saved.")
        return redirect(url_for("main.view_me"))
    return render_template("users/user_form.html", form=form)


@user_bl.get("/users/")
@login_required
def list_user():
    page = request.args.get("page", 1, type=int)
    group_id = request.args.get("group_id", type=int)
    users = User.query

    if group_id:
        # filter users by group id
        users = users.filter(User.groups.any(Group.id == group_id))

    users = users.paginate(
        page=page,
        max_per_page=current_app.config.get("PAGINATION_MAX_PER_PAGE"),
        error_out=False,
    )

    return render_template(
        "users/user_list.html",
        users=users,
        # passing users again for pagination
        pagination=users,
    )


@user_bl.get("/users/<int:user_id>")
@login_required
def detail_user(user_id: int):
    user = User.query.get_or_404(user_id)
    return render_template("users/user_detail.html", user=user)


@user_bl.route("/users/<int:user_id>", methods=["GET", "POST"])
@login_required
@role_required([Roles.admin])
def update_user(user_id: int):
    """ "Admin can fully update user and their role"""
    user = User.query.get_or_404(user_id)
    form = AdminUpdateUser(obj=user)

    if form.validate_on_submit():
        user.username = form.username.data
        user.role = form.role.data

        db.session.add(current_user)
        db.session.commit()

        return redirect(url_for("user.detail_user", user_id=user_id))

    return render_template("users/user_form.html", form=form, user=user)


@user_bl.delete("/users/<int:user_id>")
@login_required
@role_required([Roles.admin])
def delete_user(user_id: int):
    user = User.query.get_or_404(user_id)
    db.session.delete(user)
    db.session.commit()

    return redirect(url_for("user.list_user"))

apps/templates/includes/footer.html
    <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid px-4">
            <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted">
                    ©Coded By <a target="_blank" href="https://github.com/OlehOryshchuk">Oleh Oryshchuk</a>
                </div>
                <div>
                    <a target="_blank" href="https://www.linkedin.com/in/oleh-oryshchuk-9b0714288/">LinkedIn</a>
                    &middot;
                </div>
            </div>
        </div>
    </footer>

apps/templates/includes/navigation.html
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="#">Ticket Manager</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
<!--            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">-->
<!--                <div class="input-group">-->
<!--                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />-->
<!--                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>-->
<!--                </div>-->
<!--            </form>-->
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{{ url_for('user.view_me') }}">Me</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>

apps/templates/includes/pagination.html
<div class="datatable-bottom">
    <div class="datatable-info">
        Showing {{ pagination.page }} to {{ pagination.per_page }} of {{ pagination.total }} entries
    </div>
    <nav class="datatable-pagination">
        <ul class="datatable-pagination-list">
            {% if pagination.has_prev %}
            <li class="datatable-pagination-list-item">
                <a href="{{ url_for(request.endpoint, page=pagination.prev_num, per_page=per_page, search=search) }}" class="datatable-pagination-list-item-link" aria-label="Previous">
                    ‹
                </a>
            </li>
            {% endif %}
            {% for page_num in pagination.iter_pages() %}
            {% if page_num %}
            <li class="datatable-pagination-list-item {% if page_num == pagination.page %}datatable-active{% endif %}">
                <a href="{{ url_for(request.endpoint, page=page_num, per_page=per_page, search=search) }}" class="datatable-pagination-list-item-link">{{ page_num }}</a>
            </li>
            {% else %}
            <li class="datatable-pagination-list-item datatable-disabled"><span class="datatable-pagination-list-item-link">...</span></li>
            {% endif %}
            {% endfor %}
            {% if pagination.has_next %}
            <li class="datatable-pagination-list-item">
                <a href="{{ url_for(request.endpoint, page=pagination.next_num, per_page=per_page, search=search) }}" class="datatable-pagination-list-item-link" aria-label="Next">
                    ›
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>

apps/templates/includes/scripts.html
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="/static/assets/js/scripts.js"></script>

apps/templates/includes/sidebar.html
<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
        <div class="nav">
            <div class="sb-sidenav-menu-heading">Interface</div>
            <div>
                <nav class="sb-sidenav-menu-nested nav">
                    <a class="nav-link" href="{{ url_for('user.list_user') }}">Users</a>
                    <a class="nav-link" href="{{ url_for('group.list_group') }}">Groups</a>
                    <a class="nav-link" href="{{ url_for('ticket.list_ticket') }}">Tickets</a>
                </nav>
            </div>
        </div>
    </div>
    <div class="sb-sidenav-footer">
        <div class="small">Logged in as:</div>
        {{ current_user.username }}
    </div>
</nav>