apps/routes/user.py
from flask import (
    Blueprint,
    render_template,
    flash,
    redirect,
    url_for,
    current_app,
    request,
)

from flask_login import current_user, login_required

from apps.models import User, Group, Roles
from apps.forms import UpdateUser, AdminUpdateUser
from apps import db
from apps.utils import role_required


user_bl = Blueprint("user", __name__)

# Endpoints for User model


@user_bl.get("/")
def index():
    return "Hello"


@user_bl.get("/users/me")
@login_required
def view_me():
    return render_template("users/user_detail.html", user=current_user)


@user_bl.route("/users/me/edit", methods=["GET", "PATCH"])
@login_required
def update_me():
    form = UpdateUser(obj=current_user)
    if form.validate_on_submit():
        current_user.username = form.username.data
        db.session.add(current_user)
        db.session.commit()

        flash("Your changes have been saved.")
        return redirect(url_for("main.view_me"))
    return render_template("users/user_form.html", form=form)


@user_bl.get("/users/")
@login_required
def list_user():
    page = request.args.get("page", 1, type=int)
    group_id = request.args.get("group_id", type=int)
    users = User.query

    if group_id:
        # filter users by group id
        users = users.filter(User.groups.any(Group.id == group_id))

    users = users.paginate(
        page=page,
        max_per_page=current_app.config.get("PAGINATION_MAX_PER_PAGE"),
        error_out=False,
    )

    return render_template(
        "users/user_list.html",
        users=users,
        # passing users again for pagination
        pagination=users,
    )


@user_bl.get("/users/<int:user_id>")
@login_required
def detail_user(user_id: int):
    user = User.query.get_or_404(user_id)
    return render_template("users/user_detail.html", user=user)


@user_bl.route("/users/<int:user_id>", methods=["GET", "POST"])
@login_required
@role_required([Roles.admin])
def update_user(user_id: int):
    """ "Admin can fully update user and their role"""
    user = User.query.get_or_404(user_id)
    form = AdminUpdateUser(obj=user)

    if form.validate_on_submit():
        user.username = form.username.data
        user.role = form.role.data

        db.session.add(current_user)
        db.session.commit()

        return redirect(url_for("user.detail_user", user_id=user_id))

    return render_template("users/user_form.html", form=form, user=user)


@user_bl.delete("/users/<int:user_id>")
@login_required
@role_required([Roles.admin])
def delete_user(user_id: int):
    user = User.query.get_or_404(user_id)
    db.session.delete(user)
    db.session.commit()

    return redirect(url_for("user.list_user"))

apps/templates/users/user_detail.html
{% extends "layouts/base.html" %}

{% block title %}
  User
{% endblock %}

{% block content %}
  <div class="container mt-8">
    <h1>
      Username: {{ user.username }}
      {% if user == current_user %}
        <a href="{{ url_for('user.update_me') }}" class="btn btn-primary"> Update</a>
      {% endif %}

      {% if user.role.value == 'Admin' %}
        <a href="{{ url_for('user.delete_user', user_id=user.id) }}" class="btn btn-danger"> Delete</a>
      {% endif %}

    </h1>

    <p><strong>Role: </strong>{{ user.role.value }}</p>
    <hr>
  </div>
{% endblock %}

apps/templates/users/user_form.html
{% extends "layouts/base.html" %}

{% block title %}
    Update
{% endblock %}

{% block content %}
<div class="container  mt-8">
    <h1>Update</h1>
    <div class="card-body">

        <form role="form" method="post" action="">
            {{ form.csrf_token }}
            {{ form.hidden_tag() }}

            <div class="form-group">
                <label class="small mb-1" for="username">Username</label>
                {{ form.username(placeholder="Username", class="form-control") }}
            </div>
            {% if form.role %}
                <div class="form-group">
                    <label class="small mb-1" for="role">Role</label>
                    {{ form.username(placeholder="Role", class="form-control") }}
                </div>
            {% endif %}
            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                {{ form.submit(class_='btn btn-primary') }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

apps/templates/users/user_list.html
{% extends "layouts/base.html" %}

{% block title %} Users {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Users</h1>

        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                User table
            </div>
            <div class="card-body">
                <table id="datatablesSimple">
                  <thead>
                      <tr>
                          <th>Username</th>
                          <th>Role</th>
                      </tr>
                  </thead>
                  <tfoot>
                      <tr>
                          <th>Username</th>
                          <th>Role</th>
                      </tr>
                  </tfoot>
                  <tbody>
                    {% for user in users %}
                      <tr>
                        <td>
                          <a
                              href="{{ url_for('user.detail_user', user_id=user.id) }}">{{ user.username }}
                          </a>
                        </td>
                        <td>{{ user.role.value }}</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
      {% include 'includes/pagination.html' %}
    </div>
  </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script>
        window.addEventListener('DOMContentLoaded', event => {
            const datatablesSimple = document.getElementById('datatablesSimple');
            if (datatablesSimple) {
                new simpleDatatables.DataTable(datatablesSimple, {
                    paging: false, // Disable pagination
                    searchable: false, // Disable search
                });
            }
        });
    </script>

{% endblock javascripts %}